// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1kOTqr0HLBIxzVj_spO0PX5Or534_mCk',
    appId: '1:274218906646:web:d433e1961767ab8839f137',
    messagingSenderId: '274218906646',
    projectId: 'spotify-clone-f68d4',
    authDomain: 'spotify-clone-f68d4.firebaseapp.com',
    storageBucket: 'spotify-clone-f68d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQfwL73RPrvOx1jqUalRDgbek1OcMMdSg',
    appId: '1:274218906646:android:dc89aaba4674fc4439f137',
    messagingSenderId: '274218906646',
    projectId: 'spotify-clone-f68d4',
    storageBucket: 'spotify-clone-f68d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMviL7uxn3BtW75n2TWpp2knkW08KhS_U',
    appId: '1:274218906646:ios:94021b4be5732e0639f137',
    messagingSenderId: '274218906646',
    projectId: 'spotify-clone-f68d4',
    storageBucket: 'spotify-clone-f68d4.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMviL7uxn3BtW75n2TWpp2knkW08KhS_U',
    appId: '1:274218906646:ios:94021b4be5732e0639f137',
    messagingSenderId: '274218906646',
    projectId: 'spotify-clone-f68d4',
    storageBucket: 'spotify-clone-f68d4.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1kOTqr0HLBIxzVj_spO0PX5Or534_mCk',
    appId: '1:274218906646:web:9d1b2f9baaf1001039f137',
    messagingSenderId: '274218906646',
    projectId: 'spotify-clone-f68d4',
    authDomain: 'spotify-clone-f68d4.firebaseapp.com',
    storageBucket: 'spotify-clone-f68d4.appspot.com',
  );
}
